---
title: Radkit
source: ./docs
destination: _gh_pages
collections:
  docs:
    title: Docs
    output: true
    permalink: '/docs/:path/'
defaults:
- scope:
    path: ''
    type: docs
  values:
    layout: docs
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
